name: PhilosophyToday
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: 0.3.3
  cached_network_image: 2.5.0
  google_fonts: 1.1.2
  material_design_icons_flutter: 4.0.5855
  flutter_html: 1.2.0
  flappy_search_bar: ^1.7.2
  expandable: ^4.1.4
  flutter_launcher_icons: ^0.8.1
  firebase_auth: ^0.14.0+5
  firebase_core:
  firebase_analytics:
  google_sign_in:
  cloud_firestore:
  rxdart:
  image_picker: ^0.6.7+22
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.27
  html_unescape: ^1.0.2
  provider: ^3.1.0
  share: ^0.6.5+4
  url_launcher: ^5.7.10
  dio: 3.0.10
  day_night_switcher: ^0.1.1+1
  google_nav_bar: ^4.0.2
  flutter_spinkit: ^4.0.0
  animated_bottom_navigation_bar: ^0.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_native_splash: ^0.2.9
  hive_generator: ^0.8.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/Icon/icon.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/noSearch.png
    - assets/images/notFound.png
    - assets/images/search.png
    - assets/Icon/icon.png
    - assets/images/user.png
    - assets/images/googleLogo.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
